project_id = "qczcwyqpnxknqbmwpvna"

[functions.notify-lead]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.process-email-drip]
verify_jwt = false

[functions.jobber-oauth]
verify_jwt = false

[functions.jobber-sync]
verify_jwt = false

[functions.terminal-connection-token]
verify_jwt = false

[functions.terminal-create-payment]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.send-sms]
verify_jwt = false

[functions.approve-quote]
verify_jwt = false

[functions.process-review-queue]
verify_jwt = false

[functions.receive-external-lead]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.get-invoice-public]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal-request]
verify_jwt = false

[functions.track-event]
verify_jwt = false

[functions.customer-portal-data]
verify_jwt = false

[functions.process-sms-queue]
verify_jwt = false

[functions.update-visit-status]
verify_jwt = false
