// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-businesses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Reconnect this integration and sign in." }],
    isError: true
  };
}
function dbError(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }]
  };
}

// src/lib/mcp/tools/list-businesses.ts
var list_businesses_default = defineTool({
  name: "list_businesses",
  title: "List businesses",
  description: "List the businesses (tenants) the signed-in user can access, with their ids. Use an id as business_id for other tools.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("businesses").select("id, name, public_brand_name, shortcode").order("name");
    if (error) return dbError(error.message);
    return jsonResult({ businesses: data ?? [] });
  }
});

// src/lib/mcp/tools/list-leads.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_leads_default = defineTool2({
  name: "list_leads",
  title: "List leads",
  description: "List recent leads (newest first), optionally filtered by lead status or business. Returns name, phone, email, service requested, status and created date.",
  inputSchema: {
    business_id: z.string().uuid().optional().describe("Limit to one business (see list_businesses)."),
    lead_status: z.string().optional().describe("Filter by lead status, e.g. new, contacted, quoted, won, lost."),
    limit: z.number().int().optional().describe("Max leads to return, 1-100. Default 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ business_id, lead_status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabase.from("platform_leads").select(
      "id, business_id, inquiry_name, inquiry_phone, inquiry_email, requested_service, lead_status, lead_source, urgency_level, message, created_at"
    ).order("created_at", { ascending: false }).limit(take);
    if (business_id) query = query.eq("business_id", business_id);
    if (lead_status) query = query.eq("lead_status", lead_status);
    const { data, error } = await query;
    if (error) return dbError(error.message);
    return jsonResult({ count: data?.length ?? 0, leads: data ?? [] });
  }
});

// src/lib/mcp/tools/create-lead.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var create_lead_default = defineTool3({
  name: "create_lead",
  title: "Create lead",
  description: "Create a new lead for a business. Provide business_id from list_businesses; if omitted and the user can access exactly one business, that one is used.",
  inputSchema: {
    inquiry_name: z2.string().trim().min(1).describe("Contact name."),
    business_id: z2.string().uuid().optional().describe("Target business id."),
    inquiry_phone: z2.string().trim().optional().describe("Contact phone number."),
    inquiry_email: z2.string().trim().optional().describe("Contact email address."),
    requested_service: z2.string().trim().optional().describe("Service the lead asked about."),
    message: z2.string().trim().optional().describe("Notes or the customer's message."),
    lead_source: z2.string().trim().optional().describe("Where the lead came from. Defaults to 'mcp'.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let businessId = input.business_id;
    if (!businessId) {
      const { data: businesses, error: bizError } = await supabase.from("businesses").select("id").limit(2);
      if (bizError) return dbError(bizError.message);
      if (!businesses || businesses.length !== 1) {
        return dbError("business_id is required. Call list_businesses and pass the correct id.");
      }
      businessId = businesses[0].id;
    }
    const { data, error } = await supabase.from("platform_leads").insert({
      business_id: businessId,
      inquiry_name: input.inquiry_name,
      inquiry_phone: input.inquiry_phone ?? null,
      inquiry_email: input.inquiry_email ?? null,
      requested_service: input.requested_service ?? null,
      message: input.message ?? null,
      lead_source: input.lead_source ?? "mcp"
    }).select("id, business_id, inquiry_name, lead_status, created_at").single();
    if (error) return dbError(error.message);
    return jsonResult({ lead: data });
  }
});

// src/lib/mcp/tools/search-customers.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var search_customers_default = defineTool4({
  name: "search_customers",
  title: "Search customers",
  description: "Search customers by name, company, phone or email. Returns contact details plus yearly-trimming and check-preference flags.",
  inputSchema: {
    query: z3.string().trim().min(1).describe("Name, company, phone or email fragment to search for."),
    business_id: z3.string().uuid().optional().describe("Limit to one business (see list_businesses)."),
    limit: z3.number().int().optional().describe("Max customers to return, 1-50. Default 15.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, business_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const take = Math.min(Math.max(limit ?? 15, 1), 50);
    const term = query.replace(/[%,()]/g, " ").trim();
    if (!term) return dbError("Provide a searchable term.");
    let request = supabase.from("platform_customers").select(
      "id, business_id, display_name, company_name, phone, email, customer_status, yearly_trimming, prefers_check, created_at"
    ).or(
      [
        `display_name.ilike.%${term}%`,
        `company_name.ilike.%${term}%`,
        `phone.ilike.%${term}%`,
        `email.ilike.%${term}%`
      ].join(",")
    ).order("display_name").limit(take);
    if (business_id) request = request.eq("business_id", business_id);
    const { data, error } = await request;
    if (error) return dbError(error.message);
    return jsonResult({ count: data?.length ?? 0, customers: data ?? [] });
  }
});

// src/lib/mcp/tools/list-jobs.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_jobs_default = defineTool5({
  name: "list_jobs",
  title: "List jobs",
  description: "List jobs scheduled in a date range (defaults to the next 7 days), optionally filtered by status or business. Returns job number, title, status, schedule and total.",
  inputSchema: {
    business_id: z4.string().uuid().optional().describe("Limit to one business (see list_businesses)."),
    status: z4.string().optional().describe("Filter by job status, e.g. scheduled, in_progress, completed."),
    from_date: z4.string().optional().describe("Start date, YYYY-MM-DD. Defaults to today."),
    to_date: z4.string().optional().describe("End date, YYYY-MM-DD. Defaults to 7 days after the start date."),
    limit: z4.number().int().optional().describe("Max jobs to return, 1-100. Default 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ business_id, status, from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    const start = from_date ? /* @__PURE__ */ new Date(`${from_date}T00:00:00Z`) : /* @__PURE__ */ new Date();
    if (Number.isNaN(start.getTime())) return dbError("from_date must be a valid YYYY-MM-DD date.");
    const end = to_date ? /* @__PURE__ */ new Date(`${to_date}T23:59:59Z`) : new Date(start.getTime() + 7 * 24 * 60 * 60 * 1e3);
    if (Number.isNaN(end.getTime())) return dbError("to_date must be a valid YYYY-MM-DD date.");
    let query = supabase.from("platform_jobs").select(
      "id, business_id, job_number, title, status, job_type, scheduled_start, scheduled_end, total, customer_id, description"
    ).is("deleted_at", null).gte("scheduled_start", start.toISOString()).lte("scheduled_start", end.toISOString()).order("scheduled_start", { ascending: true }).limit(take);
    if (business_id) query = query.eq("business_id", business_id);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return dbError(error.message);
    return jsonResult({
      range: { from: start.toISOString(), to: end.toISOString() },
      count: data?.length ?? 0,
      jobs: data ?? []
    });
  }
});

// src/lib/mcp/tools/list-unpaid-invoices.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var list_unpaid_invoices_default = defineTool6({
  name: "list_unpaid_invoices",
  title: "List unpaid invoices",
  description: "List invoices that are not paid or voided, oldest issue date first, with balance due, payment method and due date.",
  inputSchema: {
    business_id: z5.string().uuid().optional().describe("Limit to one business (see list_businesses)."),
    limit: z5.number().int().optional().describe("Max invoices to return, 1-100. Default 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ business_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabase.from("platform_invoices").select(
      "id, business_id, invoice_number, billing_name, status, payment_method, total, amount_paid, balance_due, issue_date, due_date, sent_at"
    ).is("deleted_at", null).is("paid_at", null).is("voided_at", null).order("issue_date", { ascending: true, nullsFirst: false }).limit(take);
    if (business_id) query = query.eq("business_id", business_id);
    const { data, error } = await query;
    if (error) return dbError(error.message);
    const outstanding = (data ?? []).reduce((sum, row) => sum + Number(row.balance_due ?? row.total ?? 0), 0);
    return jsonResult({ count: data?.length ?? 0, total_outstanding: outstanding, invoices: data ?? [] });
  }
});

// src/lib/mcp/tools/list-yearly-trimming-clients.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_yearly_trimming_clients_default = defineTool7({
  name: "list_yearly_trimming_clients",
  title: "List yearly trimming clients",
  description: "List customers flagged as yearly trimming (recurring annual) clients, newest additions first, with how they were flagged.",
  inputSchema: {
    business_id: z6.string().uuid().optional().describe("Limit to one business (see list_businesses)."),
    limit: z6.number().int().optional().describe("Max customers to return, 1-200. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ business_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const take = Math.min(Math.max(limit ?? 50, 1), 200);
    let query = supabase.from("platform_customers").select(
      "id, business_id, display_name, phone, email, yearly_trimming_source, yearly_trimming_added_at, customer_status"
    ).eq("yearly_trimming", true).order("yearly_trimming_added_at", { ascending: false, nullsFirst: false }).limit(take);
    if (business_id) query = query.eq("business_id", business_id);
    const { data, error } = await query;
    if (error) return dbError(error.message);
    return jsonResult({ count: data?.length ?? 0, customers: data ?? [] });
  }
});

// src/lib/mcp/index.ts
var projectRef = "qczcwyqpnxknqbmwpvna";
var mcp_default = defineMcp({
  name: "gulf-coast-palms",
  title: "Gulf Coast Palms",
  version: "0.1.0",
  instructions: "Tools for the Gulf Coast Palms field-service platform. Start with `list_businesses` to get the business_id for the tenant you are working in, then read leads, customers, jobs, unpaid invoices, and the yearly-trimming roster. `create_lead` adds a new inbound lead. All data is scoped to the signed-in user's access.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_businesses_default,
    list_leads_default,
    create_lead_default,
    search_customers_default,
    list_jobs_default,
    list_unpaid_invoices_default,
    list_yearly_trimming_clients_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
